version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: room-booker-db
    environment:
      POSTGRES_USER: room
      POSTGRES_PASSWORD: room
      POSTGRES_DB: roombooker
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
